// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuoqoxtobyuuzgbfizsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1b3FveHRvYnl1dXpnYmZpenNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDYxMjYsImV4cCI6MjA2ODUyMjEyNn0.WEqKoCA60h759nA61n7KprGdej-Bwo6gepelsZk580c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});